[rocks]

[plugins]
"rocks.nvim" = "2.46.1"
"rocks-git.nvim" = "2.5.6"
"rocks-config.nvim" = "3.1.2"
"decasify.nvim" = "0.11.1"
"conform.nvim" = "9.1.0"

[plugins.guttermarks]
git = "dimtion/guttermarks.nvim"
rev = "fb8aa3f552a10f37cc095409b2676a202ef5bd2b"
branch = "main"

[plugins.tagbar]
git = "preservim/tagbar"
rev = "7bfffca1f121afb7a9e38747500bf5270e006bb1"
branch = "master"
ignore_tags = true

[plugins.neomake]
git = "benekastah/neomake"
rev = "584f882b9f991245374e7e7d7d1f78bae90b7a35"
branch = "master"

[plugins.fastfold]
git = "Konfekt/FastFold"
rev = "c1ddfa1a0e00316d1161ce11438ec980348b8cb9"
branch = "master"
ignore_tags = true

[plugins.lsp-lines]
git = "https://git.sr.ht/~whynothugo/lsp_lines.nvim"
rev = "v3.0.0"
branch = "main"

[plugins.monokai-nightasty]
git = "polirritmico/monokai-nightasty.nvim"
rev = "91b0798334534394d77b0b6e6089fe0655b241b3"
branch = "main"
ignore_tags = true

[plugins.match-visual]
git = "aaron-p1/match-visual.nvim"
rev = "c1e14a9a28772f7c2e9332243c1557ab51a3c9d7"
branch = "main"

[plugins.vim-just]
git = "NoahTheDuke/vim-just"
rev = "c13e317dda76ea01c2521cbed2a5c552a96951bd"
branch = "main"

[plugins.smartbraces]
git = "Konfekt/vim-smartbraces"
rev = "e576898c59d206c95f44813667961f48ca025b05"
branch = "master"
ignore_tags = true

[plugins.sentence-chopper]
git = "Konfekt/vim-sentence-chopper"
rev = "1.5"
branch = "master"

[plugins.stylua]
git = "ckipp01/stylua-nvim"
rev = "ce59a353f02938cba3e0285e662fcd3901cd270f"
branch = "main"

[plugins.augment]
git = "augmentcode/augment.vim"
rev = "v0.42.0"
opt = true
branch = "main"

[config]
plugins_dir = "rocks"
